### ISSUE TITLE
plotly github dependecy blocks pip install

### ISSUE THREAD

**Issue by carlbalmer** [rlworkgroup/viskit#11]
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
viskit depends on plotly@ https://api.github.com/repos/plotly/plotly.py/tarball/2594076e29584ede2d09f2aa40a8a195b3f3fc66

**Comment by ryanjulian** [comment]
@carlbalmer PEP517 support is spotty, and depends on which environment manager and version of Python you are using.

Can you report which Python version and environment manager (system-wide, virtualenv, conda, pipenv, poetry, etc.) you are using?
